import { build } from './build.js';

export const FOOD = build('food', 'foo', [
  ['e', 'Pizza', 'cheese|italian|slice|round', 'foods'],
  ['e', 'Bread', 'bake|loaf|butter|slice', 'foods'],
  ['e', 'Egg', 'chicken|fry|boil|yolk', 'foods'],
  ['e', 'Rice', 'grain|white|cook|boil', 'foods'],
  ['m', 'Spaghetti', 'pasta|italian|long|sauce', 'foods'],
  ['m', 'Sandwich', 'bread|filling|lunch|slice', 'foods'],
  ['m', 'Salad', 'vegetable|green|healthy|leaf', 'foods'],
  ['h', 'Barbecue', 'grill|meat|fire|smoke', 'foods'],
  ['e', 'Ice cream', 'cold|sweet|cone|melt', 'desserts'],
  ['e', 'Cake', 'birthday|sweet|bake|candle', 'desserts'],
  ['m', 'Doughnut', 'ring|sweet|hole|fry', 'desserts'],
  ['h', 'Melting ice cream', 'cold|melt|drip|sun', 'desserts'],
  ['e', 'Tea', 'hot|cup|drink|leaf', 'drinks'],
  ['e', 'Coffee', 'hot|caffeine|morning|bean', 'drinks'],
  ['m', 'Smoothie', 'blend|fruit|drink|thick', 'drinks'],
  ['h', 'Burning your tongue', 'hot|tongue|burn|drink', 'drinks'],
  ['e', 'Frying', 'oil|pan|heat|cook', 'cooking'],
  ['m', 'Chopping onions', 'onion|cry|knife|cut', 'cooking'],
  ['m', 'Boiling water', 'water|heat|bubble|hot', 'cooking'],
  ['m', 'Burning the food', 'burn|smoke|black|cook', 'cooking'],
  ['h', 'Tasting for salt', 'salt|taste|season|tongue', 'cooking'],
  ['h', 'Following a recipe', 'recipe|steps|cook|book', 'cooking'],
  ['e', 'Waiter', 'restaurant|order|serve|table', 'restaurant'],
  ['m', 'Asking for the bill', 'bill|pay|money|waiter', 'restaurant'],
  ['m', 'Ordering takeaway', 'order|deliver|phone|food', 'restaurant'],
  ['h', 'Sending food back', 'wrong|return|complain|waiter', 'restaurant'],
  ['h', 'Splitting the bill', 'bill|share|money|pay', 'restaurant'],
  ['m', 'Pepper', 'hot|spice|season|red', 'ingredients'],
  ['m', 'Sugar', 'sweet|white|tea|spoon', 'ingredients'],
  ['h', 'Too much salt', 'salt|taste|too|much', 'ingredients']
]);
