import { build } from './build.js';

export const GENERAL = build('general', 'gen', [
  // Animals
  ['e', 'Elephant', 'trunk|big|grey|safari', 'animals'],
  ['e', 'Lion', 'king|jungle|roar|mane', 'animals'],
  ['e', 'Dog', 'bark|pet|puppy|loyal', 'animals'],
  ['e', 'Chicken', 'egg|bird|farm|fry', 'animals'],
  ['e', 'Snake', 'bite|slither|poison|long', 'animals'],
  ['m', 'Giraffe', 'neck|tall|spots|zoo', 'animals'],
  ['m', 'Crocodile', 'teeth|river|reptile|bite', 'animals'],
  ['m', 'Butterfly', 'wings|colour|fly|caterpillar', 'animals'],
  ['m', 'Goat', 'meat|horns|milk|farm', 'animals'],
  ['h', 'Chameleon', 'colour|change|lizard|blend', 'animals'],
  ['h', 'Owl', 'night|wise|bird|hoot', 'animals'],
  // Objects and household
  ['e', 'Umbrella', 'rain|open|wet|cover', 'objects'],
  ['e', 'Mirror', 'reflect|glass|face|look', 'objects'],
  ['e', 'Broom', 'sweep|floor|clean|dust', 'objects'],
  ['e', 'Bucket', 'water|carry|plastic|fill', 'objects'],
  ['e', 'Ladder', 'climb|high|steps|reach', 'objects'],
  ['m', 'Fan', 'cool|blow|air|hot', 'objects'],
  ['m', 'Padlock', 'key|lock|secure|gate', 'objects'],
  ['m', 'Kettle', 'boil|water|tea|hot', 'objects'],
  ['m', 'Torch', 'light|dark|battery|shine', 'objects'],
  ['h', 'Wheelbarrow', 'push|carry|wheel|garden', 'objects'],
  ['h', 'Stapler', 'paper|office|pin|attach', 'objects'],
  // Places
  ['e', 'Hospital', 'doctor|sick|nurse|ill', 'places'],
  ['e', 'Airport', 'plane|fly|travel|luggage', 'places'],
  ['e', 'Church', 'pray|god|service|sunday', 'places'],
  ['e', 'School', 'teacher|learn|student|class', 'places'],
  ['m', 'Barbershop', 'hair|cut|clipper|shave', 'places'],
  ['m', 'Petrol station', 'fuel|car|pump|tank', 'places'],
  ['m', 'Library', 'book|quiet|read|borrow', 'places'],
  ['h', 'Courtroom', 'judge|law|case|guilty', 'places'],
  ['h', 'Prison', 'jail|lock|criminal|cell', 'places'],
  // Jobs
  ['e', 'Doctor', 'hospital|sick|treat|patient', 'jobs'],
  ['e', 'Teacher', 'school|class|student|teach', 'jobs'],
  ['e', 'Driver', 'car|drive|road|steering', 'jobs'],
  ['m', 'Tailor', 'sew|clothes|measure|cloth', 'jobs'],
  ['m', 'Mechanic', 'car|fix|engine|garage', 'jobs'],
  ['m', 'Photographer', 'camera|picture|shoot|photo', 'jobs'],
  ['m', 'Security guard', 'gate|watch|protect|uniform', 'jobs'],
  ['h', 'Accountant', 'money|numbers|book|audit', 'jobs'],
  ['h', 'Journalist', 'news|write|report|paper', 'jobs'],
  // Transport
  ['e', 'Aeroplane', 'fly|sky|airport|wings', 'transport'],
  ['e', 'Bicycle', 'ride|pedal|two|wheels', 'transport'],
  ['m', 'Helicopter', 'fly|blades|hover|sky', 'transport'],
  ['m', 'Ambulance', 'siren|hospital|emergency|sick', 'transport'],
  ['h', 'Submarine', 'water|under|sea|dive', 'transport'],
  // Activities and concepts
  ['e', 'Jogging', 'run|slow|exercise|morning', 'activities'],
  ['e', 'Dancing', 'music|move|party|steps', 'activities'],
  ['m', 'Getting a haircut', 'barber|hair|cut|salon', 'activities'],
  ['m', 'Washing clothes', 'soap|clothes|water|laundry', 'activities'],
  ['m', 'Traffic', 'car|road|slow|jam', 'activities'],
  ['h', 'Procrastination', 'later|delay|lazy|postpone', 'concepts'],
  ['h', 'Being late', 'time|late|rush|delay', 'concepts'],
  ['h', 'Missing your flight', 'plane|airport|late|miss', 'concepts'],
  ['h', 'Getting caught lying', 'lie|caught|truth|liar', 'concepts'],
  ['h', 'Awkward silence', 'quiet|awkward|talk|pause', 'concepts']
]);
