import { build } from './build.js';

// The biggest section. Forbidden clues here are the ones a Nigerian clue giver
// would reach for in the first two seconds, which is exactly what makes it fun.
export const NIGERIAN = build('nigerian', 'nga', [
  // Food
  ['e', 'Jollof rice', 'rice|party|tomato|nigerian', 'food'],
  ['e', 'Fried rice', 'rice|fry|green|party', 'food'],
  ['e', 'Amala', 'yam|black|swallow|ewedu', 'food'],
  ['e', 'Eba', 'garri|swallow|soup|yellow', 'food'],
  ['m', 'Egusi', 'melon|soup|seed|swallow', 'food'],
  ['e', 'Pounded yam', 'yam|pound|swallow|mortar', 'food'],
  ['m', 'Akara', 'bean|fry|ball|pap', 'food'],
  ['m', 'Moi moi', 'bean|steam|leaf|wrap', 'food'],
  ['e', 'Suya', 'meat|pepper|stick|roast', 'food'],
  ['m', 'Pepper soup', 'pepper|soup|hot|goat', 'food'],
  ['m', 'Ofada rice', 'rice|local|sauce|green', 'food'],
  ['e', 'Puff puff', 'fry|dough|round|sweet', 'food'],
  ['m', 'Chin chin', 'fry|crunchy|snack|flour', 'food'],
  ['e', 'Plantain', 'fry|dodo|banana|yellow', 'food'],
  ['m', 'Boli', 'plantain|roast|fire|street', 'food'],
  ['m', 'Zobo', 'drink|red|hibiscus|cold', 'food'],
  ['h', 'Small chops', 'snack|party|puff|tray', 'food'],
  ['h', 'Party jollof', 'jollof|party|smoke|rice', 'food'],
  ['m', 'Garri', 'soak|cassava|drink|eba', 'food'],
  ['h', 'Nkwobi', 'cow|foot|spicy|bowl', 'food'],
  ['m', 'Agege bread', 'bread|soft|lagos|loaf', 'food'],
  ['h', 'Ewedu', 'soup|green|slimy|amala', 'food'],
  // Music
  ['m', 'Wizkid', 'singer|afrobeats|star|music', 'music'],
  ['m', 'Davido', 'singer|afrobeats|music|omo', 'music'],
  ['m', 'Burna Boy', 'singer|grammy|music|afrobeats', 'music'],
  ['m', 'Rema', 'singer|calm|young|music', 'music'],
  ['m', 'Asake', 'singer|amapiano|music|new', 'music'],
  ['m', 'Olamide', 'rapper|indigenous|music|badoo', 'music'],
  ['m', 'Tems', 'singer|female|voice|music', 'music'],
  ['m', 'Tiwa Savage', 'singer|female|queen|music', 'music'],
  ['h', 'Phyno', 'rapper|igbo|music|indigenous', 'music'],
  ['h', 'Yemi Alade', 'singer|female|johnny|music', 'music'],
  ['e', 'Afrobeats', 'music|dance|nigeria|sound', 'music'],
  ['m', 'Shaku shaku', 'dance|street|move|leg', 'music'],
  ['m', 'Zanku', 'dance|leg|work|move', 'music'],
  ['h', 'Spraying money', 'money|party|throw|dance', 'music'],
  // Slang
  ['e', 'Omo', 'word|slang|exclaim|shock', 'slang'],
  ['e', 'Abeg', 'please|beg|slang|ask', 'slang'],
  ['e', 'Wahala', 'trouble|problem|slang|palava', 'slang'],
  ['m', 'Sapa', 'broke|money|hunger|slang', 'slang'],
  ['m', 'Japa', 'travel|leave|abroad|run', 'slang'],
  ['m', 'Gist', 'talk|story|gossip|news', 'slang'],
  ['h', 'E choke', 'too|much|slang|shock', 'slang'],
  ['e', 'No wahala', 'problem|fine|okay|trouble', 'slang'],
  ['m', 'Shege', 'suffer|hard|slang|pepper', 'slang'],
  ['h', 'Soft life', 'easy|enjoy|comfort|life', 'slang'],
  ['h', 'Gbas gbos', 'fight|argue|back|forth', 'slang'],
  // Places
  ['e', 'Lagos', 'city|traffic|state|island', 'places'],
  ['e', 'Abuja', 'capital|city|federal|state', 'places'],
  ['m', 'Ibadan', 'city|oyo|brown|roof', 'places'],
  ['m', 'Kano', 'city|north|state|kanuri', 'places'],
  ['m', 'Benin City', 'city|edo|state|oba', 'places'],
  ['m', 'Port Harcourt', 'city|rivers|oil|garden', 'places'],
  ['m', 'Enugu', 'city|coal|state|east', 'places'],
  ['m', 'Lekki', 'lagos|island|toll|estate', 'places'],
  ['m', 'Ikeja', 'lagos|mainland|airport|state', 'places'],
  ['h', 'Yaba', 'lagos|market|tech|mainland', 'places'],
  ['h', 'Victoria Island', 'lagos|island|rich|office', 'places'],
  ['h', 'Third Mainland Bridge', 'bridge|lagos|long|traffic', 'places'],
  ['h', 'Balogun market', 'market|lagos|cloth|crowd', 'places'],
  // Transport
  ['e', 'Danfo', 'bus|yellow|lagos|transport', 'transport'],
  ['e', 'Okada', 'bike|motorcycle|ride|transport', 'transport'],
  ['e', 'Keke', 'tricycle|three|napep|ride', 'transport'],
  ['m', 'BRT', 'bus|red|lane|lagos', 'transport'],
  ['e', 'Conductor', 'bus|money|shout|danfo', 'transport'],
  ['h', 'Roadside taxi', 'car|taxi|road|drop', 'transport'],
  ['h', 'Fuel queue', 'fuel|line|wait|petrol', 'transport'],
  // Life
  ['e', 'Lagos traffic', 'traffic|lagos|jam|hold', 'life'],
  ['e', 'Generator', 'light|power|noise|fuel', 'life'],
  ['e', 'NEPA', 'light|power|electricity|take', 'life'],
  ['e', 'Power outage', 'light|off|dark|power', 'life'],
  ['m', 'Nigerian wedding', 'wedding|party|aso|marry', 'life'],
  ['m', 'Family meeting', 'family|meeting|elders|talk', 'life'],
  ['m', 'NYSC', 'service|youth|khaki|camp', 'life'],
  ['m', 'ASUU strike', 'strike|school|lecturer|university', 'life'],
  ['m', 'Sunday rice', 'rice|sunday|church|jollof', 'life'],
  ['m', 'Market bargaining', 'price|market|reduce|seller', 'life'],
  ['m', 'Nigerian mum', 'mother|mum|slipper|shout', 'life'],
  ['m', 'Danfo conductor', 'bus|money|shout|change', 'life'],
  ['m', 'Owambe', 'party|dance|aso|celebrate', 'life'],
  ['m', 'Aso ebi', 'cloth|party|same|wear', 'life'],
  ['h', 'Waiting for light', 'light|power|wait|nepa', 'life'],
  ['h', 'Village trip', 'village|travel|christmas|home', 'life'],
  ['h', 'Naming ceremony', 'baby|name|ceremony|eight', 'life'],
  ['m', 'Pure water', 'water|sachet|cold|drink', 'life'],
  ['m', 'POS', 'money|withdraw|agent|card', 'life'],
  ['h', 'Recharge card', 'airtime|scratch|load|credit', 'life'],
  ['h', 'Landlord wahala', 'rent|house|landlord|pay', 'life'],
  ['h', 'Detty December', 'december|party|lagos|enjoy', 'life'],
  ['h', 'Harmattan', 'dry|dust|cold|season', 'life'],
  ['m', 'Super Eagles', 'football|team|nigeria|green', 'life'],
  ['h', 'Church vigil', 'church|night|pray|all', 'life']
]);
