import { build } from './build.js';

export const ENTERTAINMENT = build('entertainment', 'ent', [
  ['e', 'binge a whole series in one day', 'binge'],
  ['e', 'cry during a film', 'emotions'],
  ['e', 'fall asleep twenty minutes into a film', 'sleep'],
  ['m', 'spend an hour choosing what to watch', 'choosing'],
  ['e', 'spoil the ending for someone', 'spoilers'],
  ['m', 'watch the same film for the tenth time', 'rewatch'],
  ['e', 'be on their phone through the whole thing', 'phone'],
  ['m', 'look up an actor mid-scene', 'phone'],
  ['h', 'quit a series two episodes from the end', 'abandon'],
  ['e', 'talk through the important part', 'talking'],
  ['m', 'insist on subtitles', 'subtitles'],
  ['e', 'pick a horror film then refuse to watch it', 'horror'],
  ['m', 'read the book before the film', 'books'],
  ['h', 'defend a film everyone else hated', 'opinions'],
  ['e', 'watch trailers instead of the actual film', 'trailers'],
  ['m', 'start a series without the other one', 'betrayal'],
  ['e', 'suggest one more episode at midnight', 'binge'],
  ['m', 'know every actor in every scene', 'trivia'],
  ['h', 'rewatch something purely for comfort', 'comfort'],
  ['e', 'pause the film every five minutes', 'pausing'],
  ['m', 'be scared by a jump scare and deny it', 'horror'],
  ['e', 'fall asleep and claim they were watching', 'sleep'],
  ['m', 'check the reviews before deciding', 'reviews'],
  ['h', 'get properly invested in a fictional character', 'emotions'],
  ['e', 'watch a comedy over anything else', 'genre'],
  ['m', 'refuse to watch anything with subtitles', 'subtitles'],
  ['e', 'ask what just happened', 'attention'],
  ['m', 'guess the ending in the first ten minutes', 'predicting'],
  ['h', 'stay for the credits', 'credits'],
  ['e', 'suggest a documentary nobody wants', 'genre'],
  ['m', 'have a comfort show on in the background always', 'comfort'],
  ['e', 'skip the intro every time', 'skipping'],
  ['m', 'get emotionally attached to a reality show', 'reality'],
  ['h', 'quietly judge the other one’s taste', 'judgement'],
  ['e', 'take control of the remote', 'remote'],
  ['m', 'watch something twice to catch what they missed', 'rewatch'],
  ['e', 'laugh at a scene that is not funny', 'laughter'],
  ['m', 'give up on a film and go to bed', 'abandon'],
  ['h', 'remember a film wrongly for years', 'memory'],
  ['e', 'want the lights off for everything', 'setup'],
  ['m', 'complain about the ending for days', 'complaining'],
  ['h', 'watch a whole series they do not even like', 'follow-through']
]);
