import { build } from './build.js';

export const EVERYDAY = build('everyday', 'eve', [
  ['e', 'leave clothes somewhere they should not be', 'tidiness'],
  ['e', 'clean without being asked', 'chores'],
  ['e', 'procrastinate on something small for weeks', 'procrastination'],
  ['m', 'reorganise a cupboard nobody complained about', 'organisation'],
  ['e', 'leave a cup somewhere and forget it', 'tidiness'],
  ['m', 'do the washing up straight away', 'chores'],
  ['e', 'hit snooze four times', 'mornings'],
  ['m', 'make the bed every morning', 'routine'],
  ['h', 'notice something needs doing and quietly do it', 'acts-of-service'],
  ['e', 'lose the remote', 'lost-things'],
  ['m', 'buy something to solve a problem they could fix', 'shopping'],
  ['e', 'leave a drawer open', 'habits'],
  ['m', 'keep a broken thing "just in case"', 'hoarding'],
  ['e', 'take the bins out without being reminded', 'chores'],
  ['m', 'start cleaning at an unreasonable hour', 'timing'],
  ['h', 'get quietly annoyed rather than say something', 'conflict-avoidance'],
  ['e', 'forget to reply to a message for days', 'texting'],
  ['m', 'have a very specific way of folding things', 'particular'],
  ['e', 'wear the same comfortable thing constantly', 'clothes'],
  ['m', 'refuse to throw anything away', 'hoarding'],
  ['h', 'do a job properly rather than quickly', 'standards'],
  ['e', 'leave the light on in an empty room', 'habits'],
  ['m', 'be first up in the morning', 'mornings'],
  ['e', 'put something down and immediately lose it', 'lost-things'],
  ['m', 'plan the week on a Sunday', 'planning'],
  ['h', 'redo a task the other one already did', 'standards'],
  ['e', 'stay in bed on a day off', 'rest'],
  ['m', 'answer the door when nobody is expected', 'social'],
  ['e', 'forget to buy the one thing they went for', 'shopping'],
  ['m', 'do the boring admin nobody wants to do', 'admin'],
  ['h', 'notice a smell or a noise nobody else does', 'perceptive'],
  ['e', 'leave the washing in the machine overnight', 'chores'],
  ['m', 'have a strict order for doing things', 'routine'],
  ['e', 'take the longest shower', 'bathroom'],
  ['m', 'water the plants', 'home'],
  ['h', 'quietly keep the whole house running', 'acts-of-service'],
  ['e', 'lose track of time completely', 'timekeeping'],
  ['m', 'wake up before an alarm', 'mornings'],
  ['e', 'leave shoes in the middle of the floor', 'tidiness'],
  ['m', 'fix something rather than replace it', 'practical'],
  ['h', 'have a system nobody else understands', 'organisation'],
  ['e', 'fall asleep on the sofa instead of going to bed', 'sleep']
]);
