import { build } from './build.js';

export const FOOD = build('food', 'foo', [
  ['e', 'order dessert when already full', 'dessert'],
  ['e', 'eat the same meal several days running', 'repetition'],
  ['e', 'try a strange food just to see', 'adventurous'],
  ['e', 'steal food off the other one’s plate', 'sharing'],
  ['m', 'complain about a meal but finish all of it', 'complaining'],
  ['e', 'cook far too much food', 'cooking'],
  ['m', 'refuse to try something new', 'fussy'],
  ['e', 'snack right before dinner', 'snacking'],
  ['m', 'plan a whole day around one meal', 'planning'],
  ['h', 'pretend to like something to be polite', 'politeness'],
  ['e', 'eat leftovers cold from the fridge', 'leftovers'],
  ['m', 'photograph food before eating it', 'photos'],
  ['e', 'add pepper to absolutely everything', 'spice'],
  ['m', 'order the same thing at every restaurant', 'repetition'],
  ['e', 'finish the last of something and not say', 'sharing'],
  ['m', 'burn toast twice in a row', 'kitchen'],
  ['h', 'have a strong opinion about how a dish should be made', 'opinions'],
  ['e', 'eat standing up at the counter', 'habits'],
  ['m', 'save one bite for later and forget it', 'leftovers'],
  ['e', 'buy snacks for a film and finish them before it starts', 'snacking'],
  ['m', 'cook a huge meal and not want to eat it', 'cooking'],
  ['e', 'ask for extra sauce every time', 'habits'],
  ['h', 'judge a restaurant on one small detail', 'opinions'],
  ['m', 'be the one who does the washing up after', 'chores'],
  ['e', 'eat dessert first', 'dessert'],
  ['m', 'try to recreate a restaurant dish at home', 'cooking'],
  ['e', 'forget they left something in the oven', 'kitchen'],
  ['m', 'refuse to share a specific food with anyone', 'sharing'],
  ['h', 'change their favourite meal every few months', 'variety'],
  ['e', 'eat something past its date without checking', 'risk'],
  ['m', 'need a snack within an hour of a full meal', 'snacking'],
  ['e', 'order for both of them without asking', 'ordering'],
  ['m', 'send food back if it is wrong', 'restaurant'],
  ['h', 'be genuinely upset by a bad meal', 'emotions'],
  ['e', 'suggest getting food when nobody is hungry yet', 'timing'],
  ['m', 'keep a fridge full of things nobody will eat', 'waste'],
  ['e', 'drink the last of the juice and put it back', 'sharing'],
  ['m', 'make the same dish every single week', 'repetition'],
  ['h', 'insist their family makes it best', 'opinions'],
  ['e', 'eat in bed', 'habits'],
  ['m', 'be hungry ten minutes after saying they are full', 'appetite'],
  ['h', 'plan a trip mainly around what they will eat', 'travel']
]);
