import { build } from './build.js';

export const FUNNY = build('funny', 'fun', [
  ['e', 'laugh at completely the wrong moment', 'laughter'],
  ['e', 'forget why they walked into a room', 'memory'],
  ['e', 'get lost even with directions open', 'directions'],
  ['e', 'fall asleep halfway through a film', 'sleep'],
  ['e', 'trip over absolutely nothing', 'clumsy'],
  ['e', 'talk to themselves out loud', 'habits'],
  ['e', 'wave back at someone waving at a person behind them', 'awkward'],
  ['e', 'burn something they were only reheating', 'kitchen'],
  ['m', 'laugh at their own joke before finishing it', 'laughter'],
  ['m', 'forget a name two seconds after being told it', 'memory'],
  ['m', 'walk into a glass door', 'clumsy'],
  ['m', 'say "you too" when the waiter says enjoy your meal', 'awkward'],
  ['e', 'lose their phone while holding it', 'lost-things'],
  ['e', 'lose their keys in their own house', 'lost-things'],
  ['m', 'sing the wrong lyrics with total confidence', 'lyrics'],
  ['m', 'reply to a message in their head and never send it', 'texting'],
  ['e', 'take a photo where everyone else looks terrible', 'photos'],
  ['m', 'keep a screenshot for two years and never look at it', 'phone'],
  ['e', 'trip up the stairs rather than down them', 'clumsy'],
  ['m', 'argue with a self-checkout machine', 'tech'],
  ['m', 'have a full conversation with a pet', 'pets'],
  ['e', 'panic when the doorbell rings unexpectedly', 'anxiety'],
  ['m', 'pretend to know a person they absolutely do not know', 'awkward'],
  ['h', 'get emotional at an advert', 'emotions'],
  ['e', 'drop food down a clean shirt', 'clumsy'],
  ['m', 'start laughing during a serious moment', 'laughter'],
  ['e', 'forget where they parked', 'memory'],
  ['m', 'call someone by the wrong name to their face', 'awkward'],
  ['h', 'laugh at something nobody else finds funny', 'laughter'],
  ['e', 'spend ten minutes looking for glasses they are wearing', 'lost-things'],
  ['m', 'blame the wifi for their own mistake', 'tech'],
  ['e', 'take the longest possible route by accident', 'directions'],
  ['m', 'push a door clearly marked pull', 'clumsy'],
  ['h', 'find the same joke funny for a decade', 'laughter'],
  ['e', 'fall asleep in a car within ten minutes', 'sleep'],
  ['m', 'send a voice note that goes on far too long', 'texting'],
  ['e', 'forget an appointment they set that morning', 'memory'],
  ['m', 'give directions confidently while being completely wrong', 'directions'],
  ['h', 'do an impression nobody can identify', 'performance'],
  ['e', 'spill a drink reaching for something else', 'clumsy'],
  ['m', 'laugh so hard no sound comes out', 'laughter'],
  ['h', 'be the one filming when something goes wrong', 'photos']
]);
