import { build } from './build.js';

export const FUTURE = build('future', 'fut', [
  ['m', 'become famous somehow', 'fame'],
  ['m', 'start their own business', 'business'],
  ['h', 'move to another country', 'relocate'],
  ['h', 'become seriously wealthy', 'wealth'],
  ['e', 'still be doing the same job in ten years', 'career'],
  ['m', 'go back to studying', 'education'],
  ['h', 'change career completely', 'career'],
  ['m', 'end up living somewhere quiet', 'home'],
  ['e', 'have the bigger house', 'home'],
  ['m', 'learn a new language properly', 'skills'],
  ['h', 'write a book', 'creative'],
  ['m', 'go viral by accident', 'fame'],
  ['e', 'retire first', 'retirement'],
  ['m', 'take a big risk that pays off', 'risk'],
  ['h', 'give it all up and start again', 'reinvention'],
  ['e', 'be the one planning holidays in retirement', 'retirement'],
  ['m', 'own a business that keeps them up at night', 'business'],
  ['h', 'be recognised for something nobody expected', 'fame'],
  ['e', 'live closest to family', 'family'],
  ['m', 'take a year off to travel', 'travel'],
  ['h', 'still be talking about the same dream in twenty years', 'dreams'],
  ['e', 'be the one who drives everywhere', 'lifestyle'],
  ['m', 'run a marathon one day', 'fitness'],
  ['h', 'end up teaching or mentoring', 'purpose'],
  ['m', 'buy property first', 'property'],
  ['e', 'need a garden eventually', 'home'],
  ['h', 'be remembered for being kind rather than successful', 'legacy'],
  ['m', 'invent something useful', 'creative'],
  ['e', 'spoil the grandchildren', 'family'],
  ['m', 'work for themselves rather than a boss', 'career'],
  ['h', 'be content with far less than they have now', 'values'],
  ['e', 'plan retirement in detail decades early', 'planning'],
  ['m', 'become an expert in something obscure', 'skills'],
  ['h', 'surprise everyone with a life change', 'reinvention'],
  ['e', 'want a big family gathering every year', 'family'],
  ['m', 'get a qualification later in life', 'education'],
  ['h', 'take the safe option when it really matters', 'risk'],
  ['e', 'be the one who keeps everyone in touch', 'family'],
  ['m', 'live somewhere with a proper view', 'home'],
  ['h', 'look back and wish they had taken more chances', 'regret'],
  ['e', 'be first to suggest a big move', 'relocate'],
  ['m', 'still be learning something new at seventy', 'growth']
]);
