import { build } from './build.js';

export const MONEY = build('money', 'mon', [
  ['e', 'spend money impulsively', 'impulse'],
  ['e', 'save the same money for years', 'saving'],
  ['e', 'buy something purely because it is on sale', 'sales'],
  ['m', 'forget where their money went last week', 'tracking'],
  ['e', 'check their balance before every purchase', 'tracking'],
  ['m', 'pay for everyone and refuse to be paid back', 'generosity'],
  ['e', 'keep a subscription they never use', 'subscriptions'],
  ['m', 'haggle over a small amount out of principle', 'haggling'],
  ['h', 'lend money knowing it will not come back', 'lending'],
  ['e', 'buy the expensive version because it looks better', 'quality'],
  ['m', 'find a cheaper option for absolutely everything', 'bargains'],
  ['e', 'spend more on food than anything else', 'spending'],
  ['m', 'have a savings plan and actually follow it', 'saving'],
  ['h', 'panic-buy something they will regret by evening', 'impulse'],
  ['e', 'ask the price before ordering', 'caution'],
  ['m', 'treat someone for no particular reason', 'generosity'],
  ['e', 'still be using something ancient rather than replace it', 'frugal'],
  ['m', 'lose a receipt they definitely needed', 'admin'],
  ['h', 'take a financial risk on something uncertain', 'risk'],
  ['e', 'buy a gift better than the one they receive', 'gifts'],
  ['m', 'compare five shops before buying one item', 'research'],
  ['e', 'spend the last of their money on food', 'spending'],
  ['m', 'be the one who remembers who owes what', 'tracking'],
  ['h', 'change how they live entirely if they got rich', 'wealth'],
  ['e', 'forget to cancel a free trial', 'subscriptions'],
  ['m', 'insist on splitting the bill exactly', 'bills'],
  ['e', 'buy something for the house nobody asked for', 'home'],
  ['m', 'save up for one big thing rather than many small ones', 'saving'],
  ['h', 'quietly worry about money without saying so', 'stress'],
  ['e', 'pick up the tab first', 'generosity'],
  ['m', 'keep every receipt for no reason', 'admin'],
  ['e', 'spend on an experience rather than an object', 'values'],
  ['m', 'be talked into an upgrade they did not want', 'sales'],
  ['h', 'invest in something they barely understand', 'risk'],
  ['e', 'wait for payday to buy something small', 'patience'],
  ['m', 'give money to someone who asks', 'generosity'],
  ['e', 'own something expensive they have used twice', 'regret'],
  ['m', 'set a budget and break it the same day', 'budgeting'],
  ['h', 'retire early if they possibly could', 'future'],
  ['e', 'buy snacks they did not go in for', 'impulse'],
  ['m', 'know the price of everything in the fridge', 'tracking'],
  ['h', 'give away more than they can afford', 'generosity']
]);
