import { build } from './build.js';

export const MUSIC = build('music', 'mus', [
  ['e', 'sing loudly when they think nobody is listening', 'singing'],
  ['e', 'know every word to a song', 'lyrics'],
  ['e', 'replay the same song all day', 'repeat'],
  ['m', 'control the music on every journey', 'aux'],
  ['e', 'dance in the kitchen', 'dancing'],
  ['m', 'discover a song months after everyone else', 'trends'],
  ['e', 'sing the wrong words with full confidence', 'lyrics'],
  ['m', 'make a playlist for a specific mood', 'playlists'],
  ['h', 'cry at a song', 'emotions'],
  ['e', 'play music too loudly in the morning', 'volume'],
  ['m', 'skip a song after ten seconds', 'impatience'],
  ['e', 'hum something for hours without noticing', 'humming'],
  ['m', 'go to a concert alone', 'live'],
  ['h', 'defend an artist nobody else rates', 'opinions'],
  ['e', 'fall asleep with music playing', 'sleep'],
  ['m', 'know every lyric but not the artist', 'lyrics'],
  ['e', 'start a dance nobody asked for', 'dancing'],
  ['m', 'listen to one album on repeat for a month', 'repeat'],
  ['h', 'have a guilty favourite they would never admit', 'guilty'],
  ['e', 'sing along in the car with the windows down', 'singing'],
  ['m', 'be the one who queues the wrong vibe at a party', 'party'],
  ['e', 'listen to the same song from a decade ago', 'nostalgia'],
  ['m', 'learn an instrument and stop after two weeks', 'instruments'],
  ['h', 'associate a whole year with one song', 'nostalgia'],
  ['e', 'ask what song is playing', 'curiosity'],
  ['m', 'refuse to hand over the aux', 'aux'],
  ['e', 'listen to music while doing literally everything', 'habits'],
  ['m', 'know the words to an advert jingle', 'jingles'],
  ['h', 'change their whole taste in music suddenly', 'variety'],
  ['e', 'play a song and immediately play it again', 'repeat'],
  ['m', 'shout the one line they know in a whole song', 'lyrics'],
  ['e', 'put on headphones to avoid a conversation', 'avoidance'],
  ['m', 'buy tickets the moment they go on sale', 'live'],
  ['h', 'genuinely enjoy silence more than music', 'quiet'],
  ['e', 'have a hype song before going out', 'party'],
  ['m', 'ruin a song by overplaying it', 'repeat'],
  ['e', 'sing in the shower every single day', 'singing'],
  ['m', 'discover an artist and tell everyone for a week', 'enthusiasm'],
  ['h', 'remember exactly where they were when they first heard a song', 'nostalgia'],
  ['e', 'make everyone listen to one specific song', 'sharing'],
  ['m', 'fall asleep at a concert', 'live'],
  ['h', 'have wildly different taste in private than in public', 'guilty']
]);
