import { build } from './build.js';

export const NIGERIAN = build('nigerian', 'nga', [
  ['e', 'eat jollof rice three days in a row', 'naija-food'],
  ['e', 'spend ₦5,000 on a random craving', 'naija-money'],
  ['e', 'understand new Nigerian slang immediately', 'naija-slang'],
  ['m', 'survive a long Nigerian road trip in good spirits', 'naija-travel'],
  ['e', 'argue about which Nigerian food is best', 'naija-debate'],
  ['e', 'add pepper to food that is already peppery', 'naija-food'],
  ['m', 'know every word of a new Afrobeats song first', 'naija-music'],
  ['e', 'be the last to leave an owambe', 'naija-culture'],
  ['m', 'dance first at a party', 'naija-culture'],
  ['e', 'complain about Lagos traffic the whole way', 'naija-lagos'],
  ['m', 'leave the house three hours early because of traffic', 'naija-lagos'],
  ['e', 'finish a plate of amala and ask what is for dinner', 'naija-food'],
  ['m', 'take jollof to a party and claim it is the best', 'naija-food'],
  ['e', 'shout at the TV during a Super Eagles match', 'naija-football'],
  ['m', 'argue about Arsenal versus Chelsea', 'naija-football'],
  ['e', 'buy suya on the way home', 'naija-food'],
  ['m', 'know a guy who knows a guy', 'naija-life'],
  ['e', 'greet everyone in the compound', 'naija-culture'],
  ['m', 'still be talking about December plans in March', 'naija-culture'],
  ['h', 'move back to their home state one day', 'naija-life'],
  ['e', 'run out of data at the worst moment', 'naija-life'],
  ['m', 'blame NEPA before checking anything else', 'naija-life'],
  ['e', 'call someone for directions instead of using a map', 'naija-travel'],
  ['m', 'have an opinion on every Big Brother contestant', 'naija-entertainment'],
  ['e', 'watch a Nollywood film to the end', 'nollywood'],
  ['m', 'cry at a Nollywood ending', 'nollywood'],
  ['e', 'use "abeg" in a serious conversation', 'naija-slang'],
  ['m', 'explain Nigerian slang to someone who does not get it', 'naija-slang'],
  ['e', 'take an extra plate of food home from a party', 'naija-culture'],
  ['m', 'insist on paying for everyone at the restaurant', 'naija-money'],
  ['h', 'know the exact price of tomatoes this week', 'naija-money'],
  ['e', 'prefer Lagos energy over Abuja calm', 'naija-cities'],
  ['m', 'get emotional about their village at Christmas', 'naija-culture'],
  ['e', 'order pepper soup on a hot day', 'naija-food'],
  ['m', 'know all the words to an old highlife song', 'naija-music'],
  ['e', 'be first to hear about a new spot in town', 'naija-lagos'],
  ['m', 'haggle at the market for sport', 'naija-money'],
  ['h', 'speak their local language fluently', 'naija-culture'],
  ['e', 'suggest small chops for everything', 'naija-food'],
  ['m', 'plan a trip to Calabar for the carnival', 'naija-travel'],
  ['e', 'drink zobo over anything else', 'naija-food'],
  ['h', 'genuinely miss home the moment they leave', 'naija-life']
]);
