import { build } from './build.js';

export const PERSONALITY = build('personality', 'per', [
  ['e', 'overthink a very simple decision', 'overthinking'],
  ['e', 'start a conversation with a stranger', 'social'],
  ['m', 'stay calm when everything goes wrong', 'composure'],
  ['e', 'change their mind at the last minute', 'indecision'],
  ['e', 'be ready first', 'timekeeping'],
  ['m', 'read every review before buying anything', 'research'],
  ['e', 'say yes to plans they secretly do not want', 'people-pleasing'],
  ['m', 'hold a grudge over something small', 'grudges'],
  ['h', 'apologise for something that was not their fault', 'people-pleasing'],
  ['e', 'make a list for a two-item task', 'organisation'],
  ['m', 'lose their temper in traffic', 'temper'],
  ['e', 'need a plan before leaving the house', 'planning'],
  ['m', 'go completely quiet when they are stressed', 'stress'],
  ['h', 'pretend to be fine when they are not', 'vulnerable'],
  ['e', 'be the loudest in a group', 'social'],
  ['m', 'volunteer to speak in front of people', 'confidence'],
  ['e', 'give up on a task halfway through', 'follow-through'],
  ['m', 'reread a message before sending it five times', 'overthinking'],
  ['h', 'notice something is wrong before anyone says anything', 'perceptive'],
  ['e', 'take the last biscuit without hesitating', 'boldness'],
  ['m', 'talk their way out of trouble', 'charm'],
  ['e', 'be late without stressing about it', 'timekeeping'],
  ['m', 'stay up far too late for no reason', 'sleep'],
  ['h', 'do something out of character just to prove a point', 'stubborn'],
  ['e', 'ask for help when stuck', 'independence'],
  ['m', 'try to fix something they clearly cannot fix', 'stubborn'],
  ['e', 'get emotional over good news', 'emotions'],
  ['m', 'remember an embarrassing moment from years ago at 2am', 'overthinking'],
  ['h', 'change a strong opinion after one good argument', 'openness'],
  ['e', 'be the responsible one in a group', 'responsibility'],
  ['m', 'agree just to end a discussion', 'conflict-avoidance'],
  ['e', 'follow a rule nobody is enforcing', 'rules'],
  ['h', 'take criticism personally', 'sensitivity'],
  ['m', 'start something new and abandon it in a week', 'follow-through'],
  ['e', 'wing it and hope for the best', 'spontaneity'],
  ['m', 'need silence to concentrate', 'focus'],
  ['h', 'be harder on themselves than anyone else is', 'self-critical'],
  ['e', 'find a shortcut for everything', 'efficiency'],
  ['m', 'insist on doing it themselves', 'independence'],
  ['h', 'forgive quickly but never forget', 'grudges'],
  ['e', 'get excited about a small plan weeks early', 'enthusiasm'],
  ['m', 'be the calm one in an emergency', 'composure']
]);
