import { build } from './build.js';

export const RELATIONSHIP = build('relationship', 'rel', [
  ['e', 'plan a surprise date', 'surprise'],
  ['e', 'remember an important anniversary', 'dates'],
  ['e', 'apologise first after an argument', 'conflict'],
  ['m', 'suggest doing something completely spontaneous', 'spontaneity'],
  ['e', 'text first after a quiet day', 'texting'],
  ['m', 'notice a new haircut immediately', 'attention'],
  ['e', 'fall asleep first on the sofa', 'sleep'],
  ['m', 'say "I love you" out of nowhere', 'affection'],
  ['e', 'take the last piece without asking', 'sharing'],
  ['m', 'plan a whole weekend without saying a word about it', 'surprise'],
  ['h', 'bring up something from three years ago', 'conflict'],
  ['e', 'want to stay in when plans are already made', 'plans'],
  ['m', 'remember a tiny detail from a first conversation', 'memory'],
  ['e', 'ask "what are you thinking about?"', 'communication'],
  ['m', 'give a gift far too early because they cannot wait', 'gifts'],
  ['h', 'go quiet when something is genuinely wrong', 'conflict'],
  ['e', 'take a photo of the other one sleeping', 'photos'],
  ['m', 'suggest a holiday nobody budgeted for', 'travel'],
  ['e', 'want the window open at night', 'domestic'],
  ['m', 'let the other one pick the film every time', 'compromise'],
  ['h', 'apologise just to end the argument, not because they mean it', 'conflict'],
  ['e', 'hold hands in public first', 'affection'],
  ['m', 'remember exactly how the other takes their tea', 'attention'],
  ['e', 'start a conversation at midnight when the other is asleep', 'timing'],
  ['m', 'over-plan a simple night out', 'plans'],
  ['h', 'worry the other one is annoyed when they are not', 'overthinking'],
  ['e', 'save the last bit of food for the other one', 'sharing'],
  ['m', 'suggest getting a pet', 'domestic'],
  ['e', 'be the one who says goodnight first', 'routine'],
  ['h', 'need reassurance without asking for it directly', 'vulnerable'],
  ['m', 'plan something for a date months away', 'plans'],
  ['e', 'want a long hug after a bad day', 'comfort'],
  ['m', 'notice first when something is bothering the other', 'attention'],
  ['h', 'keep a small gift for years without mentioning it', 'sentiment'],
  ['e', 'change the plan five minutes before leaving', 'plans'],
  ['m', 'do the thing the other one has been putting off', 'acts-of-service'],
  ['e', 'send a message that is just a photo of something silly', 'texting'],
  ['h', 'admit they were wrong without being asked', 'conflict'],
  ['m', 'want to talk about the future at a random moment', 'future'],
  ['e', 'take up more than their share of the bed', 'domestic'],
  ['m', 'suggest doing absolutely nothing together', 'downtime'],
  ['h', 'notice a change in mood from one word', 'attention']
]);
