import { build } from './build.js';

// Teasing, not cruel. Every line here should be sayable across a table with
// both people laughing - nothing about looks, weight, money troubles or family.
export const SAVAGE = build('savage', 'sav', [
  ['e', 'start an argument over something tiny', 'arguing'],
  ['e', 'think they are always right', 'stubborn'],
  ['e', 'say "I am not angry" while clearly annoyed', 'denial'],
  ['e', 'make a decision and regret it five minutes later', 'regret'],
  ['m', 'bring up an old point mid-argument', 'arguing'],
  ['e', 'sulk without saying why', 'sulking'],
  ['m', 'take a joke slightly too personally', 'sensitivity'],
  ['e', 'double down when they know they are wrong', 'stubborn'],
  ['m', 'say "fine" and absolutely not mean it', 'denial'],
  ['h', 'keep score without admitting it', 'scorekeeping'],
  ['e', 'interrupt a story to correct a detail', 'interrupting'],
  ['m', 'give advice nobody asked for', 'advice'],
  ['e', 'reply with one word when annoyed', 'texting'],
  ['m', 'pretend to listen while thinking about something else', 'attention'],
  ['h', 'win an argument and bring it up next week', 'scorekeeping'],
  ['e', 'blame the other one for their own mistake', 'blame'],
  ['m', 'take the longest to get over something small', 'grudges'],
  ['e', 'insist they were not asleep', 'denial'],
  ['m', 'tell a story with themselves as the hero', 'exaggeration'],
  ['h', 'apologise in a way that is not really an apology', 'apologies'],
  ['e', 'change the subject when losing', 'deflection'],
  ['m', 'exaggerate slightly every time a story is retold', 'exaggeration'],
  ['e', 'point out a mistake immediately', 'nitpicking'],
  ['m', 'act calm while quietly seething', 'denial'],
  ['h', 'need the last word', 'stubborn'],
  ['e', 'complain about something they chose', 'complaining'],
  ['m', 'be mysteriously busy when there are chores', 'avoidance'],
  ['e', 'say "I told you so"', 'gloating'],
  ['m', 'volunteer the other one for something', 'volunteering'],
  ['h', 'hold a tiny grudge for an unreasonable time', 'grudges'],
  ['e', 'go quiet as a strategy', 'silence'],
  ['m', 'take credit for a joint idea', 'credit'],
  ['e', 'be unable to admit they are hungry and grumpy', 'denial'],
  ['m', 'read a message and reply three hours later', 'texting'],
  ['h', 'notice a flaw and mention it at the worst time', 'timing'],
  ['e', 'talk over the other one when excited', 'interrupting'],
  ['m', 'declare something is fine when it clearly is not', 'denial'],
  ['e', 'lose an argument and rewrite it later', 'revisionism'],
  ['m', 'get competitive over a game nobody was competing in', 'competitive'],
  ['h', 'refuse help then complain about doing it alone', 'stubborn'],
  ['e', 'ask a question and ignore the answer', 'attention'],
  ['m', 'say they do not mind and then mind a lot', 'denial']
]);
