import { build } from './build.js';

export const TRAVEL = build('travel', 'tra', [
  ['e', 'plan an entire holiday down to the hour', 'planning'],
  ['e', 'forget something important before a trip', 'packing'],
  ['e', 'suggest a spontaneous trip', 'spontaneity'],
  ['m', 'arrive at the airport far too early', 'airport'],
  ['e', 'overpack for two nights away', 'packing'],
  ['m', 'sleep through most of a flight', 'flying'],
  ['e', 'lose their boarding pass', 'lost-things'],
  ['m', 'find the best food spot within an hour', 'food'],
  ['h', 'get properly lost and enjoy it', 'wandering'],
  ['e', 'take a hundred photos of the same view', 'photos'],
  ['m', 'refuse to ask for directions', 'directions'],
  ['e', 'want to rest on the first day', 'pace'],
  ['m', 'book something without telling the other', 'surprise'],
  ['h', 'move abroad if the chance came up', 'relocate'],
  ['e', 'be stressed until they are through security', 'airport'],
  ['m', 'try to see everything in one day', 'pace'],
  ['e', 'forget a charger', 'packing'],
  ['m', 'talk to strangers in a new place', 'social'],
  ['h', 'travel somewhere completely alone', 'solo'],
  ['e', 'want the window seat', 'flying'],
  ['m', 'do no research at all before arriving', 'planning'],
  ['e', 'be first to complain about the heat', 'weather'],
  ['m', 'keep every ticket and receipt as a memory', 'sentiment'],
  ['h', 'change the plan halfway through the trip', 'flexibility'],
  ['e', 'get travel sick', 'journey'],
  ['m', 'find the cheapest possible route', 'budget'],
  ['e', 'fall asleep on the drive', 'journey'],
  ['m', 'want a beach over a city', 'preference'],
  ['h', 'go back to the same place every year', 'routine'],
  ['e', 'forget to check the weather', 'planning'],
  ['m', 'insist on trying the local food first', 'food'],
  ['e', 'be ready to leave the hotel first', 'timekeeping'],
  ['m', 'book the trip and let the other plan the days', 'roles'],
  ['h', 'get emotional at an airport goodbye', 'emotions'],
  ['e', 'take a photo of every meal abroad', 'photos'],
  ['m', 'walk twice as far as necessary to save a fare', 'budget'],
  ['e', 'want souvenirs for everyone back home', 'souvenirs'],
  ['m', 'stay up late on the first night', 'pace'],
  ['h', 'plan the next trip while still on this one', 'planning'],
  ['e', 'lose something on the journey', 'lost-things'],
  ['m', 'drive the whole way without complaining', 'driving'],
  ['h', 'survive a very long road trip in good spirits', 'endurance']
]);
