import { yesNo } from './types.js';

// Food
export const FOOD = [
  { id: 'foo-001', category: 'food', type: 'multiple_choice', difficulty: 'easy',
    text: 'What would I choose for dinner tonight?', tags: ['dinner'],
    options: ['Rice and stew', 'Pasta', 'Something grilled', 'Whatever is quickest'] },
  { id: 'foo-002', category: 'food', type: 'multiple_choice', difficulty: 'easy',
    text: 'What is one food I could eat every single day?', tags: ['favourite'],
    options: ['Rice', 'Bread', 'Chicken', 'Something sweet'] },
  { id: 'foo-003', category: 'food', type: 'this_or_that', difficulty: 'easy',
    text: 'Which would I pick?', tags: ['sweet-savoury'],
    options: ['Something sweet', 'Something savoury'] },
  { id: 'foo-004', category: 'food', type: 'this_or_that', difficulty: 'easy',
    text: 'How do I take my eggs?', tags: ['breakfast'],
    options: ['Fried', 'Scrambled'] },
  { id: 'foo-005', category: 'food', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my order at a restaurant I have never been to?', tags: ['restaurant'],
    options: ['Whatever is most popular', 'The safest thing on the menu', 'Something I cannot pronounce', 'Whatever you are having'] },
  { id: 'foo-006', category: 'food', type: 'slider', difficulty: 'medium',
    text: 'How much spice can I actually handle?', tags: ['spice'],
    labels: ['None at all', 'Bring the fire'] },
  { id: 'foo-007', category: 'food', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my comfort food when I am low?', tags: ['comfort'],
    options: ['Something hot and heavy', 'Snacks', 'Chocolate', 'Whatever my mum makes'] },
  ...[
    yesNo('foo-008', 'food', 'easy', 'Do I like pineapple on pizza?', ['pizza']),
    yesNo('foo-009', 'food', 'easy', 'Do I eat breakfast most days?', ['breakfast']),
    yesNo('foo-010', 'food', 'medium', 'Would I send food back if it was wrong?', ['restaurant']),
    yesNo('foo-011', 'food', 'medium', 'Do I actually enjoy cooking?', ['cooking']),
    yesNo('foo-012', 'food', 'hard', 'Would I try something if I did not know what was in it?', ['adventurous'])
  ],
  { id: 'foo-013', category: 'food', type: 'multiple_choice', difficulty: 'easy',
    text: 'What drink do I reach for first?', tags: ['drinks'],
    options: ['Water', 'Something fizzy', 'Juice', 'Tea or coffee'] },
  { id: 'foo-014', category: 'food', type: 'this_or_that', difficulty: 'medium',
    text: 'Which would I rather do?', tags: ['cooking'],
    options: ['Cook a proper meal', 'Order in'] },
  { id: 'foo-015', category: 'food', type: 'number', difficulty: 'medium',
    text: 'How many cups of tea or coffee do I have in a day?', tags: ['drinks'],
    min: 0, max: 10, unit: 'cups' },
  { id: 'foo-016', category: 'food', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my worst food habit?', tags: ['habits'],
    options: ['Eating too late', 'Skipping meals', 'Too many snacks', 'Never finishing my plate'] },
  { id: 'foo-017', category: 'food', type: 'multiple_choice', difficulty: 'hard',
    text: 'What food do I pretend to like more than I do?', tags: ['honesty'],
    options: ['Salad', 'Sushi', 'Very fancy food', 'Nothing, I am honest'] },
  { id: 'foo-018', category: 'food', type: 'this_or_that', difficulty: 'easy',
    text: 'Which is the better meal?', tags: ['meals'],
    options: ['Breakfast', 'Dinner'] },
  { id: 'foo-019', category: 'food', type: 'open_ended', difficulty: 'medium',
    text: 'What is the best thing I have ever eaten?', tags: ['favourite'] },
  { id: 'foo-020', category: 'food', type: 'slider', difficulty: 'medium',
    text: 'How adventurous am I with food?', tags: ['adventurous'],
    labels: ['Same thing always', 'Try anything once'] },
  { id: 'foo-021', category: 'food', type: 'multiple_choice', difficulty: 'medium',
    text: 'How do I feel about leftovers?', tags: ['habits'],
    options: ['Better the next day', 'Only if reheated properly', 'Never touch them', 'Depends entirely on the food'] },
  { id: 'foo-022', category: 'food', type: 'multiple_choice', difficulty: 'hard',
    text: 'If I could only season food with one thing forever?', tags: ['cooking'],
    options: ['Pepper', 'Salt', 'Curry', 'Maggi'] }
];
