import { yesNo } from './types.js';

// Funny - built to cause loud disagreements.
export const FUNNY = [
  { id: 'fun-001', category: 'funny', type: 'multiple_choice', difficulty: 'easy',
    text: 'Who would I trust to plan our entire holiday?', tags: ['planning'],
    options: ['{answerer}', '{partner}', 'Neither of us', 'A travel agent'] },
  { id: 'fun-002', category: 'funny', type: 'multiple_choice', difficulty: 'easy',
    text: 'What would I spend money on first if I suddenly got rich?', tags: ['money'],
    options: ['A house', 'A car', 'A ridiculous holiday', 'Something nobody would guess'] },
  { id: 'fun-003', category: 'funny', type: 'multiple_choice', difficulty: 'medium',
    text: 'Which embarrassing situation would I handle worst?', tags: ['embarrassment'],
    options: ['Falling in public', 'Forgetting someone I have met twice', 'Sending a message to the wrong person', 'Singing badly in front of people'] },
  { id: 'fun-004', category: 'funny', type: 'this_or_that', difficulty: 'easy',
    text: 'Which would I survive longer without?', tags: ['essentials'],
    options: ['My phone', 'Hot water'] },
  { id: 'fun-005', category: 'funny', type: 'multiple_choice', difficulty: 'medium',
    text: 'In a zombie apocalypse, what am I doing?', tags: ['hypothetical'],
    options: ['Leading everyone', 'Hiding well', 'Panicking loudly', 'Gone in the first hour'] },
  { id: 'fun-006', category: 'funny', type: 'this_or_that', difficulty: 'medium',
    text: 'Which is worse for me?', tags: ['pet-peeve'],
    options: ['Slow walkers', 'People who reply with one word'] },
  { id: 'fun-007', category: 'funny', type: 'multiple_choice', difficulty: 'easy',
    text: 'What do I do when I take a bad photo?', tags: ['photos'],
    options: ['Delete it immediately', 'Demand a retake', 'Post it anyway', 'Never look at it again'] },
  ...[
    yesNo('fun-008', 'funny', 'easy', 'Would I eat food that fell on the floor?', ['food']),
    yesNo('fun-009', 'funny', 'easy', 'Do I sing in the shower?', ['habits']),
    yesNo('fun-010', 'funny', 'medium', 'Have I ever pretended to know a song I did not know?', ['music']),
    yesNo('fun-011', 'funny', 'medium', 'Would I survive a week without complaining about something?', ['habits']),
    yesNo('fun-012', 'funny', 'hard', 'Do I secretly enjoy arguments I know I will win?', ['conflict'])
  ],
  { id: 'fun-013', category: 'funny', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my most unreasonable opinion?', tags: ['opinions'],
    options: ['About food', 'About music', 'About how to drive', 'About how to load a dishwasher'] },
  { id: 'fun-014', category: 'funny', type: 'this_or_that', difficulty: 'easy',
    text: 'Which would embarrass me more?', tags: ['embarrassment'],
    options: ['Tripping in public', 'Being sung to in a restaurant'] },
  { id: 'fun-015', category: 'funny', type: 'multiple_choice', difficulty: 'medium',
    text: 'If we were on a reality show, what would I be known for?', tags: ['hypothetical'],
    options: ['Being the dramatic one', 'Being the sensible one', 'Being the funny one', 'Being edited out'] },
  { id: 'fun-016', category: 'funny', type: 'number', difficulty: 'medium',
    text: 'How many alarms do I set in the morning?', tags: ['sleep'],
    min: 0, max: 10, unit: 'alarms' },
  { id: 'fun-017', category: 'funny', type: 'slider', difficulty: 'medium',
    text: 'How dramatic am I when I am slightly ill?', tags: ['drama'],
    labels: ['Carry on quietly', 'Full hospital drama'] },
  { id: 'fun-018', category: 'funny', type: 'multiple_choice', difficulty: 'hard',
    text: 'What would I never spend money on, no matter how rich?', tags: ['money'],
    options: ['Designer clothes', 'Expensive coffee', 'A gym membership', 'Anything for the house'] },
  { id: 'fun-019', category: 'funny', type: 'this_or_that', difficulty: 'medium',
    text: 'Who is the better driver?', tags: ['driving'],
    options: ['{answerer}', '{partner}'] },
  { id: 'fun-020', category: 'funny', type: 'multiple_choice', difficulty: 'easy',
    text: 'What is my reaction to a horror film?', tags: ['film'],
    options: ['Watch calmly', 'Watch through my fingers', 'Refuse entirely', 'Laugh at it'] },
  { id: 'fun-021', category: 'funny', type: 'open_ended', difficulty: 'hard',
    text: 'What is the most ridiculous thing I have ever cried at?', tags: ['emotions'] },
  { id: 'fun-022', category: 'funny', type: 'multiple_choice', difficulty: 'medium',
    text: 'If I got one superpower purely for laziness, what would it be?', tags: ['hypothetical'],
    options: ['Teleporting', 'Stopping time', 'Making food appear', 'Never needing sleep'] }
];
