import { yesNo } from './types.js';

// Lifestyle - money, habits, how I actually live.
export const LIFESTYLE = [
  { id: 'lif-001', category: 'lifestyle', type: 'multiple_choice', difficulty: 'easy',
    text: 'What would I do with unexpected money?', tags: ['money'],
    options: ['Save it', 'Spend it immediately', 'Split it', 'Give some away'] },
  { id: 'lif-002', category: 'lifestyle', type: 'this_or_that', difficulty: 'easy',
    text: 'Which would I rather spend on?', tags: ['money'],
    options: ['Things', 'Experiences'] },
  { id: 'lif-003', category: 'lifestyle', type: 'slider', difficulty: 'medium',
    text: 'How careful am I with money?', tags: ['money'],
    labels: ['Spend freely', 'Track every naira'] },
  { id: 'lif-004', category: 'lifestyle', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my biggest waste of money?', tags: ['money', 'honesty'],
    options: ['Food out', 'Clothes', 'Subscriptions', 'Things I never use'] },
  ...[
    yesNo('lif-005', 'lifestyle', 'easy', 'Do I check my bank balance often?', ['money']),
    yesNo('lif-006', 'lifestyle', 'easy', 'Do I make my bed every morning?', ['home']),
    yesNo('lif-007', 'lifestyle', 'medium', 'Would I rather be early than prepared?', ['time']),
    yesNo('lif-008', 'lifestyle', 'medium', 'Do I actually use the gym I pay for?', ['fitness']),
    yesNo('lif-009', 'lifestyle', 'hard', 'Would I take a pay cut for a calmer life?', ['work'])
  ],
  { id: 'lif-010', category: 'lifestyle', type: 'multiple_choice', difficulty: 'medium',
    text: 'What does my ideal morning look like?', tags: ['routine'],
    options: ['Up early with a plan', 'Slow and quiet', 'Straight into work', 'Sleep as long as possible'] },
  { id: 'lif-011', category: 'lifestyle', type: 'multiple_choice', difficulty: 'medium',
    text: 'How do I feel about my job right now?', tags: ['work'],
    options: ['Genuinely enjoy it', 'It pays the bills', 'Ready for a change', 'Depends on the week'] },
  { id: 'lif-012', category: 'lifestyle', type: 'this_or_that', difficulty: 'medium',
    text: 'Which matters more to me?', tags: ['values'],
    options: ['Money', 'Free time'] },
  { id: 'lif-013', category: 'lifestyle', type: 'number', difficulty: 'medium',
    text: 'How many hours a week would I ideally work?', tags: ['work'],
    min: 0, max: 80, unit: 'hours' },
  { id: 'lif-014', category: 'lifestyle', type: 'multiple_choice', difficulty: 'easy',
    text: 'What is my relationship with the gym?', tags: ['fitness'],
    options: ['Go regularly', 'Go in phases', 'Pay and never go', 'Never even considered it'] },
  { id: 'lif-015', category: 'lifestyle', type: 'multiple_choice', difficulty: 'hard',
    text: 'What would I change about how I live right now?', tags: ['growth'],
    options: ['Sleep more', 'Worry less about money', 'See people more', 'Work less'] },
  { id: 'lif-016', category: 'lifestyle', type: 'slider', difficulty: 'medium',
    text: 'How tidy do I keep my space?', tags: ['home'],
    labels: ['Organised chaos', 'Spotless'] },
  { id: 'lif-017', category: 'lifestyle', type: 'multiple_choice', difficulty: 'medium',
    text: 'How do I shop?', tags: ['shopping'],
    options: ['List and stick to it', 'Wander and decide', 'Online only', 'As fast as humanly possible'] },
  { id: 'lif-018', category: 'lifestyle', type: 'open_ended', difficulty: 'hard',
    text: 'What is the best money I have ever spent?', tags: ['money'] }
];
