import { yesNo } from './types.js';

// Music
export const MUSIC = [
  { id: 'mus-001', category: 'music', type: 'multiple_choice', difficulty: 'easy',
    text: 'What would I put on for a long drive?', tags: ['driving'],
    options: ['Afrobeats', 'R&B', 'Gospel', 'Whatever is trending'] },
  { id: 'mus-002', category: 'music', type: 'multiple_choice', difficulty: 'easy',
    text: 'What music do I play when I am in a good mood?', tags: ['mood'],
    options: ['Something loud', 'Something to dance to', 'Something familiar', 'Nothing, I like quiet'] },
  { id: 'mus-003', category: 'music', type: 'this_or_that', difficulty: 'easy',
    text: 'Which do I reach for more often?', tags: ['tempo'],
    options: ['Slow songs', 'Fast songs'] },
  { id: 'mus-004', category: 'music', type: 'multiple_choice', difficulty: 'medium',
    text: 'What do I listen to when I am sad?', tags: ['mood'],
    options: ['Sad songs, to sit in it', 'Happy songs, to snap out of it', 'The same song on repeat', 'Silence'] },
  { id: 'mus-005', category: 'music', type: 'multiple_choice', difficulty: 'medium',
    text: 'What would I do at a concert?', tags: ['live'],
    options: ['Sing every word', 'Film the whole thing', 'Stand and enjoy quietly', 'Leave before the encore'] },
  ...[
    yesNo('mus-006', 'music', 'easy', 'Do I know the actual words, or just the vibes?', ['lyrics']),
    yesNo('mus-007', 'music', 'medium', 'Would I pay a lot to see one artist live?', ['live']),
    yesNo('mus-008', 'music', 'medium', 'Do I listen to the same few songs on repeat?', ['habits']),
    yesNo('mus-009', 'music', 'hard', 'Do I like any song I would be embarrassed to admit?', ['guilty'])
  ],
  { id: 'mus-010', category: 'music', type: 'open_ended', difficulty: 'medium',
    text: 'Which artist would I most want to see live?', tags: ['artist'] },
  { id: 'mus-011', category: 'music', type: 'open_ended', difficulty: 'hard',
    text: 'What song would I say describes me?', tags: ['identity'] },
  { id: 'mus-012', category: 'music', type: 'slider', difficulty: 'medium',
    text: 'How loud do I actually play my music?', tags: ['volume'],
    labels: ['Barely audible', 'Neighbours know'] },
  { id: 'mus-013', category: 'music', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my shower singing style?', tags: ['funny'],
    options: ['Full performance', 'Quiet humming', 'Only the chorus', 'I do not sing'] },
  { id: 'mus-014', category: 'music', type: 'this_or_that', difficulty: 'medium',
    text: 'Which matters more to me in a song?', tags: ['taste'],
    options: ['The lyrics', 'The beat'] },
  { id: 'mus-015', category: 'music', type: 'multiple_choice', difficulty: 'easy',
    text: 'When do I listen to music most?', tags: ['habits'],
    options: ['Working', 'Travelling', 'Cleaning', 'Falling asleep'] },
  { id: 'mus-016', category: 'music', type: 'number', difficulty: 'hard',
    text: 'How many times could I hear my favourite song in a row before getting tired of it?', tags: ['repeat'],
    min: 1, max: 50, unit: 'times' },
  { id: 'mus-017', category: 'music', type: 'multiple_choice', difficulty: 'hard',
    text: 'If I had to perform one thing on stage, what would it be?', tags: ['performance'],
    options: ['Sing', 'Dance', 'Play an instrument', 'Absolutely nothing'] },
  { id: 'mus-018', category: 'music', type: 'this_or_that', difficulty: 'easy',
    text: 'Which would I pick for a party?', tags: ['party'],
    options: ['Old classics', 'Whatever is new'] }
];
