import { yesNo } from './types.js';

// Nigerian - food, music, cities, slang and everyday life.
// Written to sound like a conversation, not a citizenship test.
export const NIGERIAN = [
  { id: 'nga-001', category: 'nigerian', type: 'multiple_choice', difficulty: 'easy',
    text: 'Which would I choose for dinner?', tags: ['naija-food'],
    options: ['Jollof rice', 'Amala and ewedu', 'Pounded yam and egusi', 'Fried rice'] },
  { id: 'nga-002', category: 'nigerian', type: 'this_or_that', difficulty: 'easy',
    text: 'Settle it once and for all', tags: ['naija-food', 'debate'],
    options: ['Jollof rice', 'Fried rice'] },
  { id: 'nga-003', category: 'nigerian', type: 'multiple_choice', difficulty: 'easy',
    text: 'What is my go-to swallow?', tags: ['naija-food'],
    options: ['Eba', 'Amala', 'Pounded yam', 'Semo'] },
  { id: 'nga-004', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'What am I ordering from a buka?', tags: ['naija-food'],
    options: ['Rice and stew with beef', 'Swallow and soup', 'Beans and plantain', 'Whatever is fastest'] },
  { id: 'nga-005', category: 'nigerian', type: 'this_or_that', difficulty: 'easy',
    text: 'Which one?', tags: ['naija-food'],
    options: ['Suya', 'Asun'] },
  { id: 'nga-006', category: 'nigerian', type: 'this_or_that', difficulty: 'easy',
    text: 'Pick a side', tags: ['naija-food'],
    options: ['Puff puff', 'Chin chin'] },
  { id: 'nga-007', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'Which Nigerian artist would I most want to see live?', tags: ['naija-music'],
    options: ['Burna Boy', 'Wizkid', 'Davido', 'Asake'] },
  { id: 'nga-008', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is playing in my car on a Lagos morning?', tags: ['naija-music'],
    options: ['Afrobeats', 'Gospel', 'Old highlife or juju', 'A podcast, not music'] },
  { id: 'nga-009', category: 'nigerian', type: 'this_or_that', difficulty: 'medium',
    text: 'Which era do I rate higher?', tags: ['naija-music'],
    options: ['Afrobeats now', 'The 2000s classics'] },
  { id: 'nga-010', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'Which Nigerian city would I rather spend a weekend in?', tags: ['naija-cities'],
    options: ['Lagos', 'Abuja', 'Ibadan', 'Port Harcourt'] },
  { id: 'nga-011', category: 'nigerian', type: 'this_or_that', difficulty: 'medium',
    text: 'Where would I rather live?', tags: ['naija-cities'],
    options: ['Lagos energy', 'Abuja calm'] },
  ...[
    yesNo('nga-012', 'nigerian', 'easy', 'Do I put pepper in almost everything?', ['naija-food']),
    yesNo('nga-013', 'nigerian', 'easy', 'Can I handle proper Nigerian pepper?', ['naija-food']),
    yesNo('nga-014', 'nigerian', 'medium', 'Would I survive a week without rice?', ['naija-food']),
    yesNo('nga-015', 'nigerian', 'medium', 'Do I watch the Super Eagles when they play?', ['naija-football']),
    yesNo('nga-016', 'nigerian', 'medium', 'Do I still watch Nollywood films?', ['nollywood']),
    yesNo('nga-017', 'nigerian', 'hard', 'Would I move back to my home state if I could?', ['naija-life'])
  ],
  { id: 'nga-018', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my reaction to Lagos traffic?', tags: ['naija-life'],
    options: ['Leave very early', 'Complain the whole way', 'Music and patience', 'Avoid going out entirely'] },
  { id: 'nga-019', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my owambe energy?', tags: ['naija-culture'],
    options: ['First to arrive', 'There for the food', 'On the dance floor', 'Leaves early quietly'] },
  { id: 'nga-020', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'Which slang am I most likely to use?', tags: ['naija-slang'],
    options: ['Omo', 'Abeg', 'No wahala', 'E choke'] },
  { id: 'nga-021', category: 'nigerian', type: 'multiple_choice', difficulty: 'easy',
    text: 'What is my drink at a party?', tags: ['naija-culture'],
    options: ['Malt', 'Chapman', 'Zobo', 'Just water'] },
  { id: 'nga-022', category: 'nigerian', type: 'multiple_choice', difficulty: 'hard',
    text: 'Which Nigerian dish would I say I make best?', tags: ['naija-food', 'cooking'],
    options: ['Jollof', 'Egusi', 'Stew', 'Nothing, I do not cook'] },
  { id: 'nga-023', category: 'nigerian', type: 'this_or_that', difficulty: 'medium',
    text: 'Which would I pick for breakfast?', tags: ['naija-food'],
    options: ['Akara and pap', 'Bread and egg'] },
  { id: 'nga-024', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'Which Premier League side would I claim?', tags: ['naija-football'],
    options: ['Arsenal', 'Chelsea', 'Manchester United', 'I do not follow football'] },
  { id: 'nga-025', category: 'nigerian', type: 'open_ended', difficulty: 'hard',
    text: 'Which Nigerian song takes me straight back to my childhood?', tags: ['naija-music', 'memory'] },
  { id: 'nga-026', category: 'nigerian', type: 'multiple_choice', difficulty: 'medium',
    text: 'How do I feel about December in Lagos?', tags: ['naija-culture'],
    options: ['Best time of the year', 'Too crowded and expensive', 'Only for the food', 'I travel out instead'] },
  { id: 'nga-027', category: 'nigerian', type: 'slider', difficulty: 'medium',
    text: 'How well do I speak my local language?', tags: ['naija-culture'],
    labels: ['Barely a word', 'Completely fluent'] },
  { id: 'nga-028', category: 'nigerian', type: 'this_or_that', difficulty: 'easy',
    text: 'Which is the better soup?', tags: ['naija-food', 'debate'],
    options: ['Egusi', 'Okra'] },
  { id: 'nga-029', category: 'nigerian', type: 'multiple_choice', difficulty: 'hard',
    text: 'What do I miss most when I am away from home?', tags: ['naija-life'],
    options: ['The food', 'The people', 'The noise and energy', 'Nothing, honestly'] },
  { id: 'nga-030', category: 'nigerian', type: 'open_ended', difficulty: 'medium',
    text: 'Which Nigerian city would I take you to first?', tags: ['naija-cities'] }
];
