import { yesNo } from './types.js';

// Personality - how I am wired and how I behave.
export const PERSONALITY = [
  { id: 'per-001', category: 'personality', type: 'multiple_choice', difficulty: 'easy',
    text: "What's most likely to annoy me?", tags: ['irritation'],
    options: ['Being kept waiting', 'Loud chewing', 'Being interrupted', 'People who are late to reply'] },
  { id: 'per-002', category: 'personality', type: 'multiple_choice', difficulty: 'easy',
    text: 'What would I do with a completely free day?', tags: ['free-time'],
    options: ['Sleep in and do nothing', 'Go out somewhere', 'Finally tackle my to-do list', 'See friends or family'] },
  { id: 'per-003', category: 'personality', type: 'multiple_choice', difficulty: 'medium',
    text: "What's something I could never live without?", tags: ['essentials'],
    options: ['My phone', 'Music', 'Good food', 'Alone time'] },
  { id: 'per-004', category: 'personality', type: 'this_or_that', difficulty: 'easy',
    text: 'Which am I more?', tags: ['temperament'],
    options: ['Morning person', 'Night person'] },
  { id: 'per-005', category: 'personality', type: 'this_or_that', difficulty: 'medium',
    text: 'How do I make decisions?', tags: ['decisions'],
    options: ['Gut feeling', 'Weigh everything first'] },
  { id: 'per-006', category: 'personality', type: 'slider', difficulty: 'medium',
    text: 'How organised am I really?', tags: ['organisation'],
    labels: ['Complete chaos', 'Everything labelled'] },
  { id: 'per-007', category: 'personality', type: 'multiple_choice', difficulty: 'medium',
    text: 'How do I handle stress?', tags: ['stress'],
    options: ['Go quiet', 'Talk it out', 'Keep busy', 'Distract myself completely'] },
  { id: 'per-008', category: 'personality', type: 'multiple_choice', difficulty: 'hard',
    text: 'What do I like most about myself?', tags: ['self'],
    options: ['My sense of humour', 'My loyalty', 'My drive', 'My calm'] },
  { id: 'per-009', category: 'personality', type: 'multiple_choice', difficulty: 'hard',
    text: 'What am I hardest on myself about?', tags: ['self', 'vulnerable'],
    options: ['Not doing enough', 'How I look', 'Past decisions', 'Letting people down'] },
  ...[
    yesNo('per-010', 'personality', 'easy', 'Do I read the instructions before starting?', ['habits']),
    yesNo('per-011', 'personality', 'easy', 'Am I usually early?', ['time']),
    yesNo('per-012', 'personality', 'medium', 'Do I hold grudges?', ['conflict']),
    yesNo('per-013', 'personality', 'medium', 'Would I say I am competitive?', ['competitive']),
    yesNo('per-014', 'personality', 'hard', 'Do I actually enjoy small talk?', ['social'])
  ],
  { id: 'per-015', category: 'personality', type: 'this_or_that', difficulty: 'medium',
    text: 'Which describes me better?', tags: ['temperament'],
    options: ['Overthinker', 'Act first, think later'] },
  { id: 'per-016', category: 'personality', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my first reaction to bad news?', tags: ['stress'],
    options: ['Go practical immediately', 'Need a moment alone', 'Call someone', 'Pretend it is fine'] },
  { id: 'per-017', category: 'personality', type: 'slider', difficulty: 'medium',
    text: 'How much of a risk taker am I?', tags: ['risk'],
    labels: ['Play it safe', 'Jump first'] },
  { id: 'per-018', category: 'personality', type: 'multiple_choice', difficulty: 'easy',
    text: 'What kind of tired am I most often?', tags: ['energy'],
    options: ['Physically tired', 'Mentally drained', 'Bored', 'Honestly fine'] },
  { id: 'per-019', category: 'personality', type: 'number', difficulty: 'medium',
    text: 'How many hours of sleep do I actually need to feel human?', tags: ['sleep'],
    min: 3, max: 12, unit: 'hours' },
  { id: 'per-020', category: 'personality', type: 'multiple_choice', difficulty: 'hard',
    text: 'If I could change one thing about how I am, what would it be?', tags: ['growth'],
    options: ['Worry less', 'Speak up more', 'Be more patient', 'Be more consistent'] },
  { id: 'per-021', category: 'personality', type: 'this_or_that', difficulty: 'easy',
    text: 'Which would I rather be?', tags: ['values'],
    options: ['Respected', 'Liked'] },
  { id: 'per-022', category: 'personality', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my role in a group of friends?', tags: ['social'],
    options: ['The organiser', 'The joker', 'The listener', 'The one who shows up late'] },
  { id: 'per-023', category: 'personality', type: 'open_ended', difficulty: 'hard',
    text: 'What is one thing about me that surprises people?', tags: ['self'] },
  { id: 'per-024', category: 'personality', type: 'slider', difficulty: 'hard',
    text: 'How easily do I forgive?', tags: ['conflict'],
    labels: ['Never forget', 'Instantly over it'] },
  { id: 'per-025', category: 'personality', type: 'multiple_choice', difficulty: 'medium',
    text: 'What would I never admit out loud?', tags: ['funny', 'self'],
    options: ['I like the attention', 'I am often winging it', 'I care what people think', 'I am usually right'] }
];
