import { yesNo } from './types.js';

// Relationship - preferences, habits and shared experiences.
export const RELATIONSHIP = [
  { id: 'rel-001', category: 'relationship', type: 'multiple_choice', difficulty: 'easy',
    text: "What's my ideal weekend?", tags: ['weekend', 'leisure'],
    options: ['Staying home', 'Going out', 'Travelling', 'Hanging out with friends'] },
  { id: 'rel-002', category: 'relationship', type: 'multiple_choice', difficulty: 'easy',
    text: "What's my ideal date night?", tags: ['date'],
    options: ['Dinner somewhere nice', 'Movie at home', 'Long walk and talk', 'Something adventurous'] },
  { id: 'rel-003', category: 'relationship', type: 'this_or_that', difficulty: 'easy',
    text: 'Which would I rather have on a hard day?', tags: ['comfort'],
    options: ['Being held quietly', 'Being talked through it'] },
  { id: 'rel-004', category: 'relationship', type: 'multiple_choice', difficulty: 'medium',
    text: 'What kind of surprise would I enjoy most?', tags: ['surprise'],
    options: ['A planned trip', 'A thoughtful gift', 'A surprise visit', 'A quiet evening arranged for me'] },
  { id: 'rel-005', category: 'relationship', type: 'multiple_choice', difficulty: 'medium',
    text: 'How do I most like to be shown love?', tags: ['love-language'],
    options: ['Words', 'Time together', 'Small acts of help', 'Physical closeness'] },
  { id: 'rel-006', category: 'relationship', type: 'this_or_that', difficulty: 'medium',
    text: 'After an argument, what do I need first?', tags: ['conflict'],
    options: ['Space to cool off', 'To talk it out immediately'] },
  { id: 'rel-007', category: 'relationship', type: 'multiple_choice', difficulty: 'medium',
    text: "What's something I'd love for us to do together but have never said?", tags: ['aspiration'],
    options: ['Take a class', 'Travel somewhere far', 'Start something together', 'Just have a week with no plans'] },
  { id: 'rel-008', category: 'relationship', type: 'slider', difficulty: 'medium',
    text: 'How much of a planner am I in this relationship?', tags: ['planning'],
    labels: ['Totally spontaneous', 'Plans everything'] },
  { id: 'rel-009', category: 'relationship', type: 'this_or_that', difficulty: 'easy',
    text: 'Which do I prefer?', tags: ['social'],
    options: ['A night in with just us', 'A night out with everyone'] },
  { id: 'rel-010', category: 'relationship', type: 'multiple_choice', difficulty: 'hard',
    text: 'What do I worry about most that I rarely mention?', tags: ['vulnerable'],
    options: ['Money', 'Time passing', 'Letting people down', 'Being misunderstood'] },
  ...[
    yesNo('rel-011', 'relationship', 'easy', 'Would I rather be the one who plans our holidays?', ['planning']),
    yesNo('rel-012', 'relationship', 'medium', 'Do I actually enjoy surprise parties?', ['surprise']),
    yesNo('rel-013', 'relationship', 'medium', 'Would I move to another country for the right opportunity?', ['future']),
    yesNo('rel-014', 'relationship', 'easy', 'Am I the one who apologises first?', ['conflict']),
    yesNo('rel-015', 'relationship', 'hard', 'Do I secretly like being fussed over when I am ill?', ['comfort'])
  ],
  { id: 'rel-016', category: 'relationship', type: 'multiple_choice', difficulty: 'easy',
    text: 'What do I most look forward to at the end of a long day?', tags: ['routine'],
    options: ['Food', 'Silence', 'A long conversation', 'Sleep'] },
  { id: 'rel-017', category: 'relationship', type: 'multiple_choice', difficulty: 'medium',
    text: 'What would make me feel most appreciated this week?', tags: ['appreciation'],
    options: ['Being told directly', 'Having something taken off my plate', 'Undivided attention', 'A small unexpected treat'] },
  { id: 'rel-018', category: 'relationship', type: 'this_or_that', difficulty: 'medium',
    text: 'Which would I rather receive?', tags: ['gift'],
    options: ['Something practical I need', 'Something sentimental I would never buy'] },
  { id: 'rel-019', category: 'relationship', type: 'number', difficulty: 'hard',
    text: 'How many times a week would I ideally want a proper date night?', tags: ['date'],
    min: 0, max: 7, unit: 'nights' },
  { id: 'rel-020', category: 'relationship', type: 'open_ended', difficulty: 'hard',
    text: "What's my favourite memory of us so far?", tags: ['memory'] },
  { id: 'rel-021', category: 'relationship', type: 'multiple_choice', difficulty: 'medium',
    text: 'What is my most annoying habit, in my own opinion?', tags: ['self-aware'],
    options: ['Being late', 'Overthinking', 'Leaving things everywhere', 'Talking too much'] },
  { id: 'rel-022', category: 'relationship', type: 'this_or_that', difficulty: 'easy',
    text: 'Which do I find more romantic?', tags: ['romance'],
    options: ['A grand gesture', 'A quiet consistent one'] },
  { id: 'rel-023', category: 'relationship', type: 'slider', difficulty: 'medium',
    text: 'How much do I enjoy being the centre of attention?', tags: ['social'],
    labels: ['Hate it', 'Live for it'] },
  { id: 'rel-024', category: 'relationship', type: 'multiple_choice', difficulty: 'hard',
    text: 'What would I say is the best thing about us?', tags: ['us'],
    options: ['We laugh a lot', 'We talk properly', 'We are a good team', 'We give each other room'] },
  { id: 'rel-025', category: 'relationship', type: 'open_ended', difficulty: 'medium',
    text: "What's the first thing I noticed about you?", tags: ['memory'] },
  { id: 'rel-026', category: 'relationship', type: 'multiple_choice', difficulty: 'medium',
    text: 'Where would I most want to be proposed to, or to propose?', tags: ['future'],
    options: ['Somewhere private', 'Somewhere beautiful and far away', 'Surrounded by family', 'Completely unplanned'] },
  { id: 'rel-027', category: 'relationship', type: 'this_or_that', difficulty: 'medium',
    text: 'Which bothers me more?', tags: ['conflict'],
    options: ['Being ignored', 'Being rushed'] },
  { id: 'rel-028', category: 'relationship', type: 'multiple_choice', difficulty: 'easy',
    text: 'Who is more likely to fall asleep first?', tags: ['habits'],
    options: ['{answerer}', '{partner}', 'We both fight it', 'Depends on the day'] },
  { id: 'rel-029', category: 'relationship', type: 'slider', difficulty: 'hard',
    text: 'How much do I need alone time to feel normal?', tags: ['space'],
    labels: ['Barely any', 'A lot'] },
  { id: 'rel-030', category: 'relationship', type: 'multiple_choice', difficulty: 'hard',
    text: 'What would I want us to be better at?', tags: ['growth'],
    options: ['Communicating', 'Making time', 'Handling money', 'Trying new things'] }
];
